package telegram

// Code generated from functions/src/services/responseFormatter.ts. DO NOT EDIT.
//
// iconEmoji maps a Lucide icon name to the emoji the Telegram bot renders, and
// categoryEmoji is the by-category-name fallback used when a transaction or
// breakdown row carries no icon. Both tables are lifted verbatim from the
// legacy backend so replies stay byte-identical.

var iconEmoji = map[string]string{
	"Wallet":           "👛",
	"PiggyBank":        "🐷",
	"DollarSign":       "💵",
	"CreditCard":       "💳",
	"Banknote":         "💵",
	"Coins":            "🪙",
	"TrendingUp":       "📈",
	"TrendingDown":     "📉",
	"BarChart":         "📊",
	"BarChart2":        "📊",
	"PieChart":         "📊",
	"LineChart":        "📈",
	"Receipt":          "🧾",
	"Calculator":       "🧮",
	"Percent":          "💯",
	"CircleDollarSign": "💰",
	"BadgeDollarSign":  "💰",
	"Briefcase":        "💼",
	"Building":         "🏢",
	"Building2":        "🏛️",
	"Factory":          "🏭",
	"Landmark":         "🏛️",
	"Store":            "🏪",
	"ShoppingCart":     "🛒",
	"Package":          "📦",
	"Boxes":            "📦",
	"Archive":          "🗄️",
	"FileText":         "📄",
	"ClipboardList":    "📋",
	"Utensils":         "🍴",
	"Coffee":           "☕",
	"Pizza":            "🍕",
	"Beer":             "🍺",
	"Wine":             "🍷",
	"Milk":             "🥛",
	"IceCream2":        "🍦",
	"Cake":             "🍰",
	"Cookie":           "🍪",
	"Apple":            "🍎",
	"Salad":            "🥗",
	"Soup":             "🍲",
	"Sandwich":         "🥪",
	"Beef":             "🥩",
	"Fish":             "🐟",
	"Egg":              "🥚",
	"CupSoda":          "🥤",
	"Martini":          "🍸",
	"UtensilsCrossed":  "🍽️",
	"ChefHat":          "👨‍🍳",
	"Car":              "🚗",
	"Bus":              "🚌",
	"Bike":             "🚲",
	"Plane":            "✈️",
	"Train":            "🚆",
	"Ship":             "🚢",
	"Fuel":             "⛽",
	"ParkingCircle":    "🅿️",
	"Navigation":       "🧭",
	"Map":              "🗺️",
	"MapPin":           "📍",
	"Compass":          "🧭",
	"Globe":            "🌐",
	"Anchor":           "⚓",
	"Rocket":           "🚀",
	"Truck":            "🚚",
	"Sailboat":         "⛵",
	"Tractor":          "🚜",
	"ShoppingBag":      "🛍️",
	"Gift":             "🎁",
	"Tag":              "🏷️",
	"Tags":             "🏷️",
	"Ticket":           "🎫",
	"Gem":              "💎",
	"Crown":            "👑",
	"Shirt":            "👕",
	"Glasses":          "👓",
	"Watch":            "⌚",
	"Scissors":         "✂️",
	"Sparkles":         "✨",
	"Star":             "⭐",
	"Heart":            "❤️",
	"Flower":           "🌸",
	"Flower2":          "🌺",
	"Palette":          "🎨",
	"Paintbrush":       "🖌️",
	"Smartphone":       "📱",
	"Laptop":           "💻",
	"Monitor":          "🖥️",
	"Tv":               "📺",
	"Tablet":           "📱",
	"Camera":           "📷",
	"Headphones":       "🎧",
	"Speaker":          "🔊",
	"Radio":            "📻",
	"Wifi":             "📶",
	"Bluetooth":        "📶",
	"Battery":          "🔋",
	"Cable":            "🔌",
	"Cpu":              "💾",
	"HardDrive":        "💿",
	"Printer":          "🖨️",
	"Mouse":            "🖱️",
	"Keyboard":         "⌨️",
	"Gamepad":          "🎮",
	"Joystick":         "🕹️",
	"Home":             "🏠",
	"Bed":              "🛏️",
	"Sofa":             "🛋️",
	"Lamp":             "💡",
	"LampDesk":         "🕯️",
	"Lightbulb":        "💡",
	"Zap":              "⚡",
	"Plug":             "🔌",
	"Thermometer":      "🌡️",
	"Fan":              "💨",
	"AirVent":          "💨",
	"Droplet":          "💧",
	"Droplets":         "💦",
	"Flame":            "🔥",
	"Snowflake":        "❄️",
	"Wind":             "💨",
	"Hammer":           "🔨",
	"Wrench":           "🔧",
	"Key":              "🔑",
	"Lock":             "🔒",
	"DoorOpen":         "🚪",
	"Trash2":           "🗑️",
	"Recycle":          "♻️",
	"Leaf":             "🍃",
	"TreePine":         "🌲",
	"Trees":            "🌳",
	"HeartPulse":       "💗",
	"Stethoscope":      "🩺",
	"Pill":             "💊",
	"Syringe":          "💉",
	"Activity":         "📈",
	"Dumbbell":         "🏋️",
	"PersonStanding":   "🚶",
	"Footprints":       "👣",
	"Brain":            "🧠",
	"Eye":              "👁️",
	"Ear":              "👂",
	"Hand":             "✋",
	"CircleUser":       "👤",
	"Smile":            "😊",
	"Frown":            "☹️",
	"Sun":              "☀️",
	"Moon":             "🌙",
	"CloudSun":         "⛅",
	"Umbrella":         "☂️",
	"Shield":           "🛡️",
	"ShieldCheck":      "🛡️",
	"BookOpen":         "📖",
	"Book":             "📚",
	"BookMarked":       "📖",
	"Notebook":         "📓",
	"GraduationCap":    "🎓",
	"School":           "🏫",
	"Pencil":           "✏️",
	"PenTool":          "🖊️",
	"Highlighter":      "🖍️",
	"Eraser":           "🧹",
	"Ruler":            "📏",
	"Backpack":         "🎒",
	"Baby":             "👶",
	"ToyBrick":         "🧸",
	"Puzzle":           "🧩",
	"Music":            "🎵",
	"Music2":           "🎶",
	"Music3":           "🎼",
	"Music4":           "🎹",
	"Mic":              "🎤",
	"Mic2":             "🎙️",
	"Video":            "📹",
	"Film":             "🎬",
	"Clapperboard":     "🎬",
	"Popcorn":          "🍿",
	"Dice1":            "🎲",
	"Dice5":            "🎲",
	"Trophy":           "🏆",
	"Medal":            "🏅",
	"Mountain":         "⛰️",
	"MountainSnow":     "🏔️",
	"Waves":            "🌊",
	"Sunrise":          "🌅",
	"Sunset":           "🌇",
	"Cloud":            "☁️",
	"CloudRain":        "🌧️",
	"CloudSnow":        "🌨️",
	"Rainbow":          "🌈",
	"Bird":             "🐦",
	"Cat":              "🐱",
	"Dog":              "🐶",
	"Bug":              "🐛",
	"Rabbit":           "🐰",
	"Squirrel":         "🐿️",
	"Tent":             "⛺",
	"Binoculars":       "🔭",
	"Flashlight":       "🔦",
	"Church":           "⛪",
	"Cross":            "✝️",
	"BookHeart":        "📖",
	"Phone":            "📞",
	"PhoneCall":        "📞",
	"Mail":             "✉️",
	"MessageCircle":    "💬",
	"Send":             "📤",
	"Share":            "↗️",
	"Users":            "👥",
	"UserPlus":         "➕",
	"UserCheck":        "✅",
	"Handshake":        "🤝",
	"PartyPopper":      "🎉",
	"Default":          "📦",
}

var categoryEmoji = map[string]string{
	"Food":           "🍔",
	"Transportation": "🚗",
	"Shopping":       "🛒",
	"Health":         "💊",
	"Entertainment":  "🎬",
	"Bills":          "📄",
	"Other":          "📦",
}

// iconEmojiDefault is iconMap['Default'] from the TypeScript source.
const iconEmojiDefault = "📦"

// fallbackEmoji is what the legacy formatter renders when neither table matches.
// It is iconMap['Default'] in the TypeScript source, which is also the literal
// fallback on the categoryEmoji branch.
const fallbackEmoji = iconEmojiDefault

// EmojiFor resolves the emoji for a row, mirroring the legacy expression
// "item.icon ? iconToEmoji(item.icon) : (CATEGORY_EMOJI[item.category] || default)".
//
// Note the asymmetry, which is deliberate: an icon that is present but unknown
// falls through iconToEmoji's own default and never consults categoryEmoji.
func EmojiFor(icon, category string) string {
	if icon != "" {
		if e, ok := iconEmoji[icon]; ok {
			return e
		}
		return fallbackEmoji
	}
	if e, ok := categoryEmoji[category]; ok {
		return e
	}
	return fallbackEmoji
}
