package telegram

import (
	"errors"

	"cloud.google.com/go/firestore"
	"github.com/gin-gonic/gin"
	"github.com/mthidayat/dompet-cerdas-go/internal/middleware"
	"github.com/mthidayat/dompet-cerdas-go/internal/modules/account"
	"github.com/mthidayat/dompet-cerdas-go/internal/modules/advisor"
	"github.com/mthidayat/dompet-cerdas-go/internal/modules/telegram/botapi"
	"github.com/mthidayat/dompet-cerdas-go/internal/modules/transaction"
	"github.com/mthidayat/dompet-cerdas-go/internal/shared/response"
)

type Handler struct {
	db                *firestore.Client
	bot               *botapi.Client
	linkService       *LinkService
	accountService    *account.Service
	accountRepo       *account.Repository
	sessions          *SessionStore
	classifier        transaction.Classifier
	transactionParser transaction.TextParser
	analyzer          transaction.ReceiptAnalyzer
	advisor           *advisor.Service
	transcriber       Transcriber
	receipts          ReceiptUploader
	webhookSecret     string
}

// NewHandler wires the Telegram handler. The account service and repository are
// required to answer queries: every reply is scoped to the account the sender's
// Telegram link points at, and the repository owns the cached category lookup
// that transaction rows are joined against.
//
// classifier and transactionParser may be nil. Category resolution then falls
// back to deterministic legs, and free-form transaction parsing falls back to the
// local parser, so the bot remains usable without Gemini.
func NewHandler(
	db *firestore.Client,
	accountService *account.Service,
	accountRepo *account.Repository,
	classifier transaction.Classifier,
	transactionParser transaction.TextParser,
	analyzer transaction.ReceiptAnalyzer,
	advisorService *advisor.Service,
	transcriber Transcriber,
	receipts ReceiptUploader,
	botToken, webhookSecret string,
) *Handler {
	bot := botapi.New(botToken)
	return &Handler{
		db:                db,
		bot:               bot,
		linkService:       NewLinkService(db, bot),
		accountService:    accountService,
		accountRepo:       accountRepo,
		sessions:          NewSessionStore(db),
		classifier:        classifier,
		transactionParser: transactionParser,
		analyzer:          analyzer,
		advisor:           advisorService,
		transcriber:       transcriber,
		receipts:          receipts,
		webhookSecret:     webhookSecret,
	}
}

func (h *Handler) LinkService() *LinkService {
	return h.linkService
}

func (h *Handler) RegisterPublic(rg *gin.RouterGroup) {
	rg.POST("/telegram/webhook", h.HandleWebhook)
}

func (h *Handler) RegisterProtected(rg *gin.RouterGroup) {
	rg.POST("/telegram/link", h.LinkAccount)
	rg.POST("/telegram/notify-success", h.NotifyLinkSuccess)
}

func mapLinkError(c *gin.Context, err error) {
	switch {
	case errors.Is(err, ErrInvalidToken):
		response.BadRequest(c, "Token wajib diisi.", "INVALID_TOKEN", nil)
	case errors.Is(err, ErrTokenNotFound):
		response.FailedPrecondition(c, "Token tidak ditemukan.", "INVALID_TOKEN")
	case errors.Is(err, ErrTokenUsed):
		response.FailedPrecondition(c, "Token sudah digunakan.", "USED_TOKEN")
	case errors.Is(err, ErrTokenExpired):
		response.FailedPrecondition(c, "Token sudah kedaluwarsa.", "EXPIRED_TOKEN")
	default:
		response.InternalError(c)
	}
}

// LinkAccount links a Telegram account using a 5-minute token generated by /start.
func (h *Handler) LinkAccount(c *gin.Context) {
	userID, ok := middleware.RequireAuth(c)
	if !ok {
		return
	}

	var req struct {
		Token string `json:"token" binding:"required"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		response.BadRequest(c, "Token wajib diisi.", "INVALID_REQUEST", err.Error())
		return
	}

	result, err := h.linkService.LinkAccount(c.Request.Context(), userID, req.Token)
	if err != nil {
		mapLinkError(c, err)
		return
	}

	response.OK(c, "Akun Telegram berhasil terhubung", result)
}

// NotifyLinkSuccess sends the Telegram confirmation message after web linking.
func (h *Handler) NotifyLinkSuccess(c *gin.Context) {
	userID, ok := middleware.RequireAuth(c)
	if !ok {
		return
	}

	var req struct {
		TelegramID  int64  `json:"telegramId" binding:"required"`
		AccountName string `json:"accountName"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		response.BadRequest(c, "Data tidak valid.", "INVALID_REQUEST", err.Error())
		return
	}

	if err := h.linkService.NotifyLinkSuccess(c.Request.Context(), userID, req.TelegramID, req.AccountName); err != nil {
		response.InternalErrorWithMessage(c, err.Error())
		return
	}

	response.OK(c, "Notifikasi berhasil dikirim ke Telegram", nil)
}
